const fs = require('fs');
const path = require('path');

// Master keyword definitions organized by core clusters
const clusters = {
  brand: {
    target: "index.html",
    seeds: [
      "blushnbloomm",
      "blushnbloomm in",
      "blushnbloomm com",
      "blushnbloomm pune",
      "blushnbloomm pimpri chinchwad",
      "blushnbloomm studio",
      "blushnbloomm floral studio",
      "blushnbloomm boutique gifting",
      "blushnbloomm reviews",
      "blushnbloomm siddhi kokate",
      "blushnbloomm whatsapp",
      "blushnbloomm instagram",
      "blushnbloomm catalog",
      "blushnbloomm portfolio",
      "bloom and blush",
      "bloom and blush pune",
      "bloom and blush floral",
      "bloom and blush boutique",
      "bloom and blush pimpri",
      "bloom and blush chinchwad",
      "bloom and blush gifts",
      "bloom and blush hampers",
      "bloom and blush money garland",
      "bloom and blush bouquets",
      "bloom and blush owner portal",
      "bloom and blush studio pune",
      "bloom & blush",
      "bloom & blush pune",
      "bloom & blush studio",
      "bloom & blush boutique gifting",
      "blush and bloom",
      "blush and bloom pune",
      "blush & bloom gifting",
      "blush & bloom floral studio",
      "siddhi kokate",
      "siddhi kokate pune",
      "siddhi kokate bloom and blush",
      "siddhi kokate floral designer",
      "siddhi kokate gifting studio",
      "siddhi kokate money garland",
      "siddhi kokate boutique",
      "bloom and blush contact number",
      "bloom and blush wedding gifting",
      "blushnbloomm price list",
      "blushnbloomm bridal bouquet",
      "blushnbloomm luxury hampers",
      "blushnbloomm collections",
      "blushnbloomm online order",
      "blushnbloomm phone number",
      "blushnbloomm address pune"
    ]
  },

  moneyGarlands: {
    target: "category.html?id=money-garlands",
    baseTerms: [
      "money garland",
      "currency garland",
      "currency note garland",
      "groom money garland",
      "groom note haar",
      "wedding money garland",
      "money haar for groom",
      "rupee note garland",
      "origami money garland",
      "origami currency garland",
      "indian wedding money garland",
      "baraat money garland",
      "groom entry money garland",
      "luxury money garland",
      "customized money garland",
      "bespoke money garland",
      "handcrafted money garland",
      "designer currency garland",
      "money garland with velvet roses",
      "zari border currency garland",
      "pearl tassel money garland",
      "damage free money garland",
      "zero pinhole currency garland",
      "safe note folding garland",
      "500 rupee note garland",
      "100 rupee note garland",
      "200 rupee note garland",
      "50 rupee note garland",
      "20 rupee note garland",
      "10 rupee note garland",
      "real currency garland",
      "fresh note garland for groom",
      "shagun currency garland",
      "roka money garland",
      "engagement money garland",
      "milni money garland",
      "punjabi groom money garland",
      "sikh groom money garland",
      "marwari wedding money garland",
      "gujarati groom currency garland",
      "maharashtrian wedding money garland",
      "royal groom note haar",
      "money garland for 50th birthday",
      "money garland for 60th birthday",
      "shashtipoorthi currency garland",
      "thread ceremony money garland",
      "munj money garland",
      "retirement money garland",
      "money garland maker in pune",
      "money garland shop pimpri chinchwad",
      "money garland wakad",
      "money garland baner",
      "money garland hinjawadi",
      "money garland kothrud",
      "money garland ravet",
      "money garland nigdi",
      "money garland aundh",
      "money garland viman nagar",
      "buy money garland online",
      "money garland price in pune",
      "money garland starting price",
      "money garland making charges",
      "how to order money garland",
      "fast delivery money garland pune",
      "wedding currency mala",
      "groom entry accessories",
      "gold zari groom haar",
      "burgundy rose money garland",
      "blush pink currency garland",
      "antique gold money garland",
      "traditional groom garland",
      "modern minimalist money garland",
      "double layer currency garland",
      "heavy royal groom money garland",
      "lightweight note garland",
      "keepsake money garland box",
      "archival currency garland packing",
      "clean note folding for weddings",
      "best money garland artist pune",
      "top rated currency garland studio",
      "money garland home delivery pune",
      "wedding cash garland",
      "groom gift money garland",
      "currency note jewelry",
      "currency necklace for wedding",
      "groom baraat haar design",
      "currency folding artist pune",
      "money garland booking whatsapp",
      "custom length currency garland",
      "24 inch groom money garland",
      "36 inch royal money garland",
      "groom garland with name tag",
      "brass calligraphy groom garland",
      "money garland for brother in law",
      "money garland for son wedding",
      "trending wedding money garlands",
      "viral groom money garland instagram",
      "money garland craft studio",
      "money garland near me pune",
      "custom groom haar pcmc",
      "designer note garland maharashtra",
      "pan india shipping money garland",
      "express money garland pune",
      "royal sovereign money garland",
      "golden aura currency garland",
      "imperial bridal family garland"
    ]
  },

  bouquets: {
    target: "category.html?id=bouquets",
    baseTerms: [
      "artisanal bouquets",
      "bridal bouquet pune",
      "wedding bouquet pune",
      "hand tied bridal bouquet",
      "luxury floral bouquet",
      "wine garden rose bouquet",
      "deep burgundy rose bouquet",
      "blush ranunculus bouquet",
      "cascading bridal bouquet",
      "preserved flower bouquet",
      "eternal preserved roses",
      "3 year preserved roses pune",
      "fresh flower bouquet delivery pune",
      "exotic wedding flowers pune",
      "eucalyptus bridal bouquet",
      "anemone floral bouquet",
      "trailing velvet ribbon bouquet",
      "silk ribbon wedding bouquet",
      "bridesmaid bouquet pune",
      "groom boutonniere pune",
      "matching corsage and boutonniere",
      "bridal entry flower bouquet",
      "wedding proposal bouquet pune",
      "anniversary flower bouquet pune",
      "birthday floral bouquet pcmc",
      "luxury florist in pimpri chinchwad",
      "boutique flower studio pune",
      "custom color bridal bouquet",
      "lehenga matching floral bouquet",
      "gown matching wedding bouquet",
      "peony and garden rose bouquet",
      "white and blush bridal flowers",
      "crimson romantic rose bouquet",
      "rustic bohemian bridal bouquet",
      "modern editorial flower bouquet",
      "preserved floral cloche bouquet",
      "dried floral arrangement pune",
      "hydration pack flower bouquet",
      "long lasting bridal flowers",
      "sustainable preserved bouquets",
      "luxury roses in round box",
      "floral styling for weddings",
      "pre wedding shoot flower bouquet",
      "maternity photoshoot floral bouquet",
      "flower bouquet wakad",
      "flower bouquet hinjawadi",
      "flower bouquet baner",
      "flower bouquet kothrud",
      "flower bouquet koregaon park",
      "flower bouquet viman nagar",
      "flower bouquet kalyani nagar",
      "flower bouquet ravet",
      "flower bouquet nigdi",
      "flower bouquet pimpri",
      "flower bouquet chinchwad",
      "order bridal bouquet online pune",
      "bridal bouquet price in pune",
      "same day bouquet delivery pune",
      "best wedding florist pune",
      "artisanal flower arrangements",
      "bespoke floral designer siddhi",
      "handcrafted flower bouquet",
      "fragrant luxury garden roses",
      "ecuadorian rose bouquet pune",
      "preserved hydrangeas and roses",
      "baby breath bridal bouquet",
      "gypsophila wedding bouquet",
      "lavender and rose bouquet",
      "pastel theme bridal bouquet",
      "vintage romance floral bouquet",
      "blush petal bridal bouquet",
      "wine and blush bridal bouquet",
      "editorial bouquet bloom and blush",
      "custom flower bouquet maker",
      "luxury floral studio near me",
      "flower bouquet for bride entry",
      "reception flower bouquet",
      "engagement flower bouquet pune",
      "roka flower bouquet",
      "flower bouquet with personalized note",
      "wax seal card with bouquet",
      "premium flower gift wrapping",
      "aesthetic flower bouquet pune",
      "instagram trending flower bouquets",
      "boutique flower shop pune",
      "flower subscription pune",
      "luxury rose arrangement pune",
      "wedding car floral styling",
      "mandap flower accents",
      "bridal table floral centerpiece",
      "floral backdrop accents",
      "flower studio pimpri chinchwad"
    ]
  },

  hampers: {
    target: "category.html?id=customized-hampers",
    baseTerms: [
      "customized hampers",
      "luxury hampers pune",
      "celebration hampers pune",
      "bespoke gift hampers",
      "customized gift boxes pune",
      "velvet trunk hamper",
      "burgundy velvet trunk hamper",
      "bride to be hamper pune",
      "groom hamper box",
      "wedding welcome hamper",
      "wedding return gift hampers",
      "bridesmaid proposal hamper",
      "groomsman gift hamper",
      "luxury trousseau hamper",
      "dry fruit hamper with brass canisters",
      "gourmet celebration hamper",
      "scented soy candle hamper",
      "handcrafted luxury gift hamper",
      "anniversary luxury hamper pune",
      "milestone birthday hamper",
      "50th birthday gift hamper",
      "baby shower gift hamper pune",
      "housewarming luxury hamper",
      "griha pravesh gift hamper",
      "corporate luxury hampers pune",
      "corporate diwali hampers pune",
      "festive gift hampers pune",
      "new year corporate gifting",
      "executive gift boxes pune",
      "personalized hampers with wax seal",
      "foil monogrammed gift boxes",
      "customized wooden keepsake trunk",
      "high end gift hampers pcmc",
      "curated luxury hampers wakad",
      "curated luxury hampers baner",
      "curated luxury hampers hinjawadi",
      "curated luxury hampers kothrud",
      "curated luxury hampers koregaon park",
      "curated luxury hampers viman nagar",
      "order custom hamper online pune",
      "luxury hamper starting price",
      "best gift hamper designer pune",
      "bespoke gifting studio siddhi kokate",
      "velvet reverie celebration hamper",
      "heritage brass and dry fruit hamper",
      "tea and honey luxury hamper",
      "chocolate and wine glass hamper",
      "artisanal spa gift hamper",
      "fragrance and candle gift box",
      "premium dry fruit presentation box",
      "wedding room hampers for guests",
      "destination wedding welcome hamper",
      "luxury hamper packing in pune",
      "gift packaging designer pune",
      "trousseau gift boxes",
      "customized gift hamper near me",
      "same day gift hamper delivery pune",
      "exclusive diwali hampers 2026",
      "raksha bandhan luxury hamper",
      "ganesh chaturthi prasad hamper",
      "navratri festive gift box",
      "valentines day luxury hamper pune",
      "mothers day celebration hamper",
      "fathers day luxury gift box",
      "clients appreciation gift box",
      "employee onboarding luxury kit",
      "custom branded corporate hampers",
      "bulk gifting hampers pune",
      "wholesale luxury gift packing",
      "personalized gift consultation whatsapp",
      "luxury hamper studio pimpri chinchwad",
      "handcrafted memory trunk",
      "luxury gift hamper for couples",
      "engagement announcement hamper",
      "save the date gift hamper",
      "wedding invitation accompaniment box",
      "royal bridal gift box",
      "bespoke luxury hamper maharashtra",
      "pan india delivery gift hampers",
      "fragile safe delivery luxury hampers",
      "top rated hamper makers pune"
    ]
  },

  weddingGifting: {
    target: "category.html?id=wedding-gifting",
    baseTerms: [
      "wedding gifting pune",
      "celebration gifting pune",
      "trousseau packing in pune",
      "trousseau packing pimpri chinchwad",
      "luxury trousseau presentation trays",
      "bridal trousseau packing pune",
      "groom trousseau packing",
      "designer saree packing trays",
      "lehenga presentation tray",
      "shagun platters pune",
      "wedding ring tray decoration pune",
      "engagement ring platter designer",
      "roka gift platter",
      "mehendi favors pune",
      "haldi giveaway hampers",
      "sangeet return gifts",
      "wedding return gifts pune",
      "luxury zardozi potlis",
      "embroidered velvet potlis",
      "dry fruit potlis for wedding",
      "ceremonial platters pune",
      "wedding jewelry tray decoration",
      "bangle tray for wedding",
      "cosmetics packing tray bridal",
      "watch and perfume tray for groom",
      "custom coin boxes for shagun",
      "silver coin presentation tray",
      "gold coin gift packaging",
      "luxury shagun envelopes pune",
      "velvet shagun envelopes",
      "silk raw edge wedding envelopes",
      "trousseau packing wakad",
      "trousseau packing baner",
      "trousseau packing hinjawadi",
      "trousseau packing kothrud",
      "trousseau packing aundh",
      "trousseau packing ravet",
      "trousseau packing nigdi",
      "trousseau packing pcmc",
      "trousseau packing maharashtra",
      "best trousseau packer in pune",
      "trousseau packing cost pune",
      "trousseau packing price list",
      "destination wedding gifting services",
      "royal wedding trousseau boxes",
      "antique brass wedding platters",
      "wooden carved trousseau trays",
      "mirror work trousseau trays",
      "floral trousseau decoration",
      "wedding gift wrapping studio",
      "bespoke trousseau studio siddhi kokate",
      "bridal trunk packaging pune",
      "wedding favor packaging",
      "custom gift tags for wedding",
      "wedding welcome basket for hotel rooms",
      "baraat welcome giveaways",
      "milni gift packing",
      "kanyadaan ceremonial items presentation",
      "mangalsutra presentation box",
      "wedding invitation box styling",
      "wedding trousseau consultation whatsapp",
      "luxury wedding trousseau bloom and blush",
      "trousseau packing near me",
      "wedding packing classes pune",
      "trousseau styling studio pune",
      "traditional maharashtrian trousseau packing",
      "north indian wedding trousseau packing",
      "marwari trousseau packing pune",
      "punjabi wedding trousseau packing",
      "gujarati lagan trousseau packing"
    ]
  },

  keepsakesAndResin: {
    target: "category.html?id=customized-gifts",
    baseTerms: [
      "customized keepsakes pune",
      "customized gifts pune",
      "flower preservation pune",
      "wedding flower preservation pune",
      "wedding varmala preservation resin",
      "jaimala preservation frame pune",
      "resin flower preservation frame",
      "preserved bridal bouquet frame",
      "resin memory clock with varmala",
      "resin nameplate with preserved flowers",
      "resin jewelry tray with wedding flowers",
      "personalized wooden keepsake box",
      "hand carved wooden memory box",
      "calligraphy letter keepsake",
      "brass calligraphy letters pune",
      "custom couple keepsake box",
      "anniversary memory frame pune",
      "baby milestone keepsake frame",
      "first year memory keepsake",
      "wedding invitation resin frame",
      "photo and floral resin block",
      "preservation of milestone flowers",
      "varmala resin artist in pune",
      "flower preservation pimpri chinchwad",
      "resin art studio pimpri chinchwad",
      "customized gifts wakad",
      "customized gifts baner",
      "customized gifts hinjawadi",
      "customized gifts kothrud",
      "customized gifts viman nagar",
      "order personalized gifts online pune",
      "customized gifts starting price",
      "best personalized gift shop pune",
      "resin floral preservation cost",
      "how to preserve wedding garland",
      "varmala preservation turnaround time",
      "safe flower drying for resin",
      "keepsake gift consultation siddhi kokate",
      "handcrafted memory chest",
      "wooden trunk with brass lock",
      "engraved keepsake box for bride",
      "couple initial wooden box",
      "wedding vow keepsake book",
      "hand written calligraphy vows",
      "keepsake gifting studio near me",
      "unique handcrafted gifts pune",
      "personalized anniversary gift pune",
      "bespoke birthday gift keepsake",
      "luxury memory preservation studio"
    ]
  },

  luxuryAddons: {
    target: "category.html?id=luxury-addons",
    baseTerms: [
      "luxury add ons",
      "preserved ecuadorian rose dome",
      "preserved rose glass cloche",
      "eternal rose in bell jar",
      "beauty and the beast rose dome pune",
      "forever rose cloche pune",
      "real rose lasting 3 years",
      "botanical glass cloche",
      "preserved floral dome gift",
      "mandap floral accents",
      "bridal hair floral jewelry pune",
      "real flower jewelry for haldi",
      "floral jewelry for mehendi pune",
      "baby breath floral hair accessory",
      "preserved rose boutonniere",
      "groom floral pocket square",
      "bridesmaid floral wrist corsage",
      "fresh floral corsage pune",
      "luxury fragrance vials for hampers",
      "custom wax seal stamp",
      "personalized brass gift charms",
      "hand dyed silk ribbons pune",
      "luxury gift packaging accessories",
      "floral dome home decor",
      "preserved botanical cloche wakad",
      "preserved rose cloche baner",
      "preserved rose cloche hinjawadi",
      "preserved rose cloche kothrud",
      "floral dome price in pune",
      "order forever rose online pune",
      "eternal rose dome delivery pune",
      "luxury desk floral accent",
      "anniversary rose cloche gift",
      "proposal forever rose dome",
      "luxury botanical studio pcmc",
      "floral accessories by siddhi kokate",
      "bespoke luxury add ons bloom and blush"
    ]
  },

  localGeoKeywords: {
    target: "index.html",
    baseTerms: [
      "florist in pimpri chinchwad",
      "florist in pune",
      "boutique florist pune",
      "flower shop pimpri chinchwad",
      "gift shop pimpri chinchwad",
      "luxury gift shop pune",
      "gifting studio in pcmc",
      "flower delivery pimpri chinchwad",
      "flower delivery pune same day",
      "online florist pcmc",
      "boutique gifting studio pune",
      "customized gifts pimpri chinchwad",
      "money garland shop near me",
      "bridal bouquet maker near me",
      "gift hampers shop near me",
      "trousseau packing near me",
      "wedding gifts shop near me",
      "florist wakad",
      "florist hinjawadi",
      "florist baner",
      "florist aundh",
      "florist kothrud",
      "florist koregaon park",
      "florist viman nagar",
      "florist kalyani nagar",
      "florist ravet",
      "florist nigdi",
      "florist pradhikaran",
      "florist akurdi",
      "florist chikhali",
      "florist moshi",
      "florist bhosari",
      "florist pimpri",
      "florist chinchwad",
      "florist bavdhan",
      "florist magarpatta",
      "florist hadapsar",
      "florist kharadi",
      "gifting wakad",
      "gifting hinjawadi",
      "gifting baner",
      "gifting kothrud",
      "gifting viman nagar",
      "gifting ravet",
      "gifting nigdi",
      "gifting pcmc",
      "gifting pune",
      "wedding gifting wakad",
      "wedding gifting baner",
      "wedding gifting hinjawadi",
      "wedding gifting kothrud",
      "trousseau packing wakad",
      "trousseau packing baner",
      "trousseau packing aundh",
      "trousseau packing kothrud",
      "trousseau packing pcmc",
      "money garland wakad",
      "money garland baner",
      "money garland hinjawadi",
      "money garland kothrud",
      "money garland pcmc",
      "money garland pune city",
      "luxury flowers wakad",
      "luxury flowers baner",
      "luxury flowers koregaon park",
      "custom hampers wakad",
      "custom hampers baner",
      "custom hampers hinjawadi",
      "custom hampers kothrud",
      "custom hampers pcmc",
      "pune florist phone number",
      "pcmc gift shop whatsapp",
      "siddhi kokate address pimpri chinchwad",
      "blushnbloomm studio address pune"
    ]
  },

  occasions: {
    target: "index.html#occasions",
    baseTerms: [
      "wedding gifts for bride and groom",
      "baraat entry accessories for groom",
      "groom garland ideas",
      "roka ceremony gift ideas",
      "engagement hampers for couple",
      "haldi ceremony floral favors",
      "mehendi celebration return gifts",
      "sangeet dance accessories",
      "50th milestone birthday gifts",
      "60th birthday gifts for father",
      "shashtipoorthi ceremony accessories",
      "golden jubilee anniversary gifts",
      "silver jubilee celebration hampers",
      "baby shower return gifts pune",
      "godh bharai hamper ideas",
      "naming ceremony cradle gifts",
      "thread ceremony munj gifts",
      "housewarming luxury gifts pune",
      "griha pravesh gift baskets",
      "corporate festive gifting pune",
      "diwali hampers for employees pune",
      "diwali gifts for corporate clients",
      "new year celebration gift hampers",
      "valentines day luxury flowers pune",
      "mothers day bouquet delivery pune",
      "fathers day custom gift box",
      "raksha bandhan brother hamper",
      "bhai dooj special gift box",
      "ganesh utsav prasad hampers",
      "navratri ceremonial gifts",
      "retirement felicitations garland",
      "luxury proposal flowers and setup",
      "anniversary celebration flowers pune",
      "congratulations luxury hamper",
      "get well soon floral arrangement",
      "luxury thank you gift hamper"
    ]
  },

  transactionalCommercial: {
    target: "index.html#contact",
    baseTerms: [
      "buy money garland online pune",
      "order groom money garland whatsapp",
      "where to get money garland made in pune",
      "how much does money garland cost",
      "money garland making price list",
      "custom money garland fast dispatch",
      "urgent money garland delivery pune",
      "order bridal bouquet online pune",
      "bridal bouquet price consultation",
      "book bridal flowers in advance",
      "luxury gift hamper online order",
      "custom hamper quotation whatsapp",
      "trousseau packing booking pune",
      "trousseau packing consultation siddhi",
      "varmala preservation order pune",
      "wedding garland resin preservation price",
      "forever rose glass cloche buy online",
      "direct whatsapp order bloom and blush",
      "blushnbloomm customer care whatsapp",
      "siddhi kokate floral studio contact",
      "boutique studio appointment pune",
      "custom gifting catalogue pdf download",
      "handcrafted luxury gifts delivery timeline",
      "pan india shipping charges blushnbloomm",
      "order bespoke gifts from pune studio",
      "gift hampers delivery wakad hinjawadi",
      "same day wedding gift delivery pune",
      "trusted wedding gifting vendor pune",
      "5 star rated florist in pune",
      "luxury gifting recommendations pune"
    ]
  }
};

// Modifiers to synthesize comprehensive high-volume long-tail combinations
const modifiers = [
  "best",
  "luxury",
  "handcrafted",
  "bespoke",
  "customized",
  "price",
  "online",
  "near me",
  "pune",
  "pimpri chinchwad"
];

// Compile all unique keywords
const keywordMap = new Map();

function addKeyword(kw, clusterName, target, intent, volumeTier) {
  const clean = kw.toLowerCase().trim().replace(/\s+/g, ' ');
  if (!clean || clean.length < 3) return;
  if (!keywordMap.has(clean)) {
    keywordMap.set(clean, {
      id: "bb-kw-" + String(keywordMap.size + 1).padStart(4, '0'),
      keyword: clean,
      cluster: clusterName,
      targetPage: target,
      intent: intent,
      volumeTier: volumeTier
    });
  }
}

// 1. Add Brand Seeds
clusters.brand.seeds.forEach(k => {
  addKeyword(k, "Brand & Brand Aliases", clusters.brand.target, "navigational", "High");
});

// 2. Add Cluster Terms directly
Object.keys(clusters).forEach(key => {
  if (key === 'brand') return;
  const group = clusters[key];
  const list = group.baseTerms || [];
  list.forEach(k => {
    let intent = "commercial";
    if (k.includes("buy") || k.includes("order") || k.includes("price") || k.includes("cost") || k.includes("charges")) {
      intent = "transactional";
    } else if (k.includes("pune") || k.includes("pcmc") || k.includes("wakad") || k.includes("near me")) {
      intent = "local";
    }
    addKeyword(k, key, group.target, intent, "Medium");
  });
});

// 3. Generate Systematic High-Intent Long-Tail Combinations to exceed 850+ keywords
const coreProducts = [
  "money garland",
  "currency garland",
  "groom note haar",
  "origami currency garland",
  "bridal bouquet",
  "wedding bouquet",
  "wine rose bouquet",
  "preserved flowers",
  "luxury hamper",
  "celebration hamper",
  "velvet trunk hamper",
  "trousseau packing",
  "wedding shagun platter",
  "ring ceremony tray",
  "varmala preservation",
  "resin flower frame",
  "preserved rose cloche",
  "customized keepsake box"
];

const locations = [
  "pune",
  "pimpri chinchwad",
  "wakad",
  "hinjawadi",
  "baner",
  "kothrud",
  "aundh",
  "ravet",
  "nigdi",
  "viman nagar",
  "koregaon park",
  "maharashtra",
  "near me"
];

const intents = [
  "best",
  "order",
  "buy",
  "customized",
  "luxury",
  "handcrafted",
  "price of",
  "cost of",
  "top rated",
  "designer"
];

// Combination 1: Intent + Product + Location (e.g. "best money garland pune", "order bridal bouquet wakad")
for (const intent of intents) {
  for (const prod of coreProducts) {
    for (const loc of locations) {
      if (keywordMap.size >= 920) break;
      const kw = `${intent} ${prod} in ${loc}`;
      const target = prod.includes("money") || prod.includes("haar") || prod.includes("currency") 
        ? "category.html?id=money-garlands" 
        : prod.includes("bouquet") || prod.includes("rose") || prod.includes("flower") 
        ? "category.html?id=bouquets"
        : prod.includes("hamper") 
        ? "category.html?id=customized-hampers"
        : prod.includes("trousseau") || prod.includes("platter") || prod.includes("tray")
        ? "category.html?id=wedding-gifting"
        : prod.includes("preservation") || prod.includes("resin") || prod.includes("keepsake")
        ? "category.html?id=customized-gifts"
        : "category.html?id=luxury-addons";
      
      addKeyword(kw, "Long-tail Geo Intent", target, intent.includes("buy") || intent.includes("order") || intent.includes("cost") ? "transactional" : "local", "Long-tail");
    }
  }
}

// Combination 2: Product + Occasion (e.g. "money garland for groom baraat", "luxury hamper for wedding anniversary")
const occasionTerms = [
  "for groom",
  "for wedding baraat",
  "for roka ceremony",
  "for wedding anniversary",
  "for bride to be",
  "for 50th birthday",
  "for 60th birthday shashtipoorthi",
  "for baby shower",
  "for housewarming celebration",
  "for corporate diwali gifting",
  "for thread ceremony munj"
];

for (const prod of coreProducts) {
  for (const occ of occasionTerms) {
    if (keywordMap.size >= 950) break;
    const kw = `${prod} ${occ}`;
    const target = prod.includes("money") || prod.includes("haar") 
      ? "category.html?id=money-garlands" 
      : prod.includes("bouquet") 
      ? "category.html?id=bouquets"
      : prod.includes("hamper") 
      ? "category.html?id=customized-hampers"
      : "index.html#occasions";
    addKeyword(kw, "Occasion Keyword Intent", target, "commercial", "Medium");
  }
}

const allKeywords = Array.from(keywordMap.values());

const output = {
  meta: {
    siteName: "Bloom&blush (blushnbloomm)",
    domain: "https://blushnbloomm.in",
    founder: "Siddhi Kokate",
    location: "Pimpri-Chinchwad, Pune, Maharashtra",
    generatedAt: new Date().toISOString(),
    totalKeywords: allKeywords.length,
    coverageStatement: "Exceeds 800+ targeted keywords for Blush&Bloom (blushnbloomm) boutique studio SEO dominance."
  },
  clustersSummary: {
    brandAndAliases: allKeywords.filter(k => k.cluster === "Brand & Brand Aliases").length,
    moneyGarlands: allKeywords.filter(k => k.targetPage.includes("money-garlands")).length,
    artisanalBouquets: allKeywords.filter(k => k.targetPage.includes("bouquets")).length,
    customizedHampers: allKeywords.filter(k => k.targetPage.includes("customized-hampers")).length,
    weddingGifting: allKeywords.filter(k => k.targetPage.includes("wedding-gifting")).length,
    keepsakesAndResin: allKeywords.filter(k => k.targetPage.includes("customized-gifts")).length,
    luxuryAddons: allKeywords.filter(k => k.targetPage.includes("luxury-addons")).length,
    geoAndOccasionLongTail: allKeywords.filter(k => k.cluster.includes("Long-tail") || k.cluster.includes("Occasion")).length
  },
  keywords: allKeywords
};

const targetPath = path.join(process.cwd(), 'data', 'seo-keywords.json');
fs.writeFileSync(targetPath, JSON.stringify(output, null, 2), 'utf-8');

console.log(`\n======================================================`);
console.log(` SUCCESS: Generated ${allKeywords.length} Targeted Keywords!`);
console.log(` Saved to: ${targetPath}`);
console.log(` Total Keywords: ${output.meta.totalKeywords}`);
console.log(` Clusters:`, output.clustersSummary);
console.log(`======================================================\n`);
